overrides:
  "class-variance-authority": "workspace:*"
  "cva": "workspace:*"
  "mdast-util-directive>mdast-util-to-markdown": "2.1.2"
  "vite": "^8.1.0"

minimumReleaseAge: 1440

packages:
  - "docs/*"
  - "examples/**"
  - "packages/**"

enablePrePostScripts: true

allowBuilds:
  "@swc/core": true
  core-js: true
  esbuild: true
  sharp: true
  svelte-preprocess: true
